seed: 42
datafiles:
    data_dir: 'data/Sentiment140-dataset/training.1600000.processed.noemoticon.csv'
    dataset_encoding: 'ISO-8859-1'

data_processing:
    train_size: 500
    val_size: 150
    test_size: 2000

hyperparameters:
    backbone: 
        object: transformers.models.canine.modeling_canine.CanineModel
        name: 'google/canine-c'
    max_epochs: 30
    batch_size: 8
    lr: 1e-5
    freeze_encoder: True
    profiler: 'simple'
    num_classes: 2

trainer:
    enable_progress_bar: False

callbacks:
    early_stopping:
        patience: 5
        min_delta: 0.05
        monitor: 'val_loss'

    checkpoint:
        save_top_k: 2
        monitor: 'val_loss'

logging:
    wandb: True
    project_name: 'wandb-sentiment-analysis'
    log_dir: 'logs'