seed: 42
datafiles:
    data_dir: '/data/Sentiment140-dataset/training.1600000.processed.noemoticon.csv'
    dataset_encoding: 'ISO-8859-1'

hyperparameters:
    backbone: 'google/canine-c'
    max_epochs: 30
    batch_size: 8
    lr: 1e-5
    freeze_encoder: 0.5
    profiler: 'simple'

callbacks:
    early_stopping:
        patience: 5
        min_delta: 0.05
        monitor: 'val_loss'

    checkpoint:
        save_top_k: 2
        monitor: 'val_loss'

logging:
    wandb: True
    project_name: 'sentiment-analysis'